### ISSUE TITLE
Blog stories widget is failing to load stories.

### ISSUE THREAD

**Issue by tatwell** [chapmanu/cascade-assets#110]
Ross reports:

> So this is the first time I am using the new blog stories widget on production and it looks like it is not pulling the data like the dev test that I checked was doing. 
> 
> Here is my production example: https://www.chapman.edu/law/1-column-modular-test.aspx
>
> And here was the dev test I was given to check: http://dev-www.chapman.edu/test-section/Mirabel%201%20Column.aspx (side note, I think the page was renamed in the backend to /test-schmid-index-schmid

**Comment by mirabelrice** [comment]
Error message in console:
>jquery.min.js:4 Mixed Content: The page at 'https://www.chapman.edu/law/1-column-modular-test.aspx' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://social.chapman.edu/top_story?url=https%3A%2F%2Fblogs.chapman.edu%2Fl…through-chapman-law-clinic%2F&source=https%3A%2F%2Fblogs.chapman.edu%2Flaw'. This request has been blocked; the content must be served over HTTPS.

**Comment by mirabelrice** [comment]
Fixed by changing request url protocol from `http` to `https`
