### ISSUE TITLE
Flexslider nav buttons display improperly on mobile

### ISSUE THREAD

**Issue by mirabelrice** [chapmanu/cascade-assets#120]
Issue discovered on the new slider masthead, which uses the [FlexSlider plugin](https://github.com/woocommerce/FlexSlider).

On mobile devices, the slide navigation buttons sometimes become out of out of sync when clicked, causing the previous nav link to remain highlighted as well as the current nav link.

The `.active-slide` class applies the red styling to the nav link that corresponds to the current slide.
The plugin seems to be correctly adding/removing this class, however the previous nav link remains red. 

The same issue can be reproduced on the plugins homepage [example](http://flexslider.woothemes.com/?_ga=1.241982978.1690128999.1481148267) . It seems to be an ongoing issue for the plugin: https://github.com/woocommerce/FlexSlider/issues/193, and it looks like it is being addressed for the next release.

**Comment by tatwell** [comment]
Trello card: https://trello.com/c/89myeC82/159-defect-on-new-www-mastheads-flexslider-slide-buttons-get-out-of-sync

**Comment by tatwell** [comment]
Product owner agreed to defer action on issue at present. Will re-open if we users notice.
