### ISSUE TITLE
In Campus map, Rinker search results in a 404 page.

### ISSUE THREAD

**Issue by tatwell** [chapmanu/cascade-assets#124]
Trello card has details:

https://trello.com/c/IDOumT6y/19-defect-rinker-search-results-in-a-404-page

**Comment by tatwell** [comment]
@sharissis-brei emailed following info about fix:

> The issue was that the form action was set to "return: false", which led to a 404 page. I've removed this and added some code to prevent the form from actually submitting if the user hits enter. The autocomplete still functions as expected.

**Comment by tatwell** [comment]
@sharissis-brei Can you identify the files you changed in Dev Cascade? Once we've identified them, @mandythomas and I will take this issue over and handle deployment. Thanks!

**Comment by sharissis-brei** [comment]
Hi @tatwell and @mandythomas, I changed /_cascade/templates/Campus Map/Landing in dev-cascade so far. No changes outside the CMS were needed.

I'll also be updating this in the production CMS shortly as well.

**Comment by tatwell** [comment]
@sharissis-brei No need to update production. We'll review changes in `/_cascade/templates/Campus Map/Landing` and handle production deployment ourselves.

If we have any questions, we'll email you or post them here (which should trigger email). Thanks.

**Comment by tatwell** [comment]
@mandythomas Diffed versions of `/_cascade/templates/Campus Map/Landing` using this site:

https://www.diffchecker.com

Changed l. 70. Was:

    <form action="return false;" id="virtualTour-searchFieldForm">

Now:

    <form action="" id="virtualTour-searchFieldForm" onsubmit="event.preventDefault()">

Works for me.

**Comment by tatwell** [comment]
@sharissis-brei I don't expect a problem. In future, we'll handle production deployment. 

@mandythomas, can you confirm fix with Ross? If confirmed, we can close this ticket.

**Comment by sharissis-brei** [comment]
Great, thanks for understanding. Let me know if you need anything else from our end.
