### ISSUE TITLE
Outstanding issues with OmniNav bar overlaying anchor points

### ISSUE THREAD

**Issue by mandythomas** [chapmanu/cascade-assets#129]
The OmniNav bar overlays the top of the page so anchors on some pages are hidden beneath the bar when you go down to that place on the page. For example:

This page (and all pages using A-Z widget) http://www.chapman.edu/a-z/index.aspx when you click on a letter.

This page (and all pages using Personnel widget) http://www.chapman.edu/admission/undergraduate/contact-us/index.aspx#shannon-crogan  which should jump to the top of Shannon Crogan's bio on the page. The anchor is auto-generated by the Personnel widget using the firstname-lastname as the anchor name.

Note, the page supplied in the last Omni-Nav Overlay Issue referenced this page http://www.chapman.edu/campus-services/marketing-communication/guidelines-and-resources/writing/index.aspx but on that page the A-Z links are simply hand-coded by the user in the wysiwyg editor when they created the page. They did not use the A-Z widget.

**Comment by tatwell** [comment]
Added to Trello: https://trello.com/c/92Fvbl9H/

**Comment by tatwell** [comment]
Dev versions of pages can be found here:

- http://dev-www.chapman.edu/a-z/index.aspx
- http://dev-www.chapman.edu/admission/undergraduate/contact-us/index.aspx#shannon-crogan

**Comment by tatwell** [comment]
Adding widgets to 2-col sample to reproduce this:

- http://localhost:3000/two_column/sample#a-z-anchors

**Comment by tatwell** [comment]
Added code to handle case where user connects externally to a page with personnel widget with anchor links. For example, click link below with server running locally:

- http://localhost:3000/two_column/sample#personnel-anchor-jane

**Comment by tatwell** [comment]
Deployed changes to staging. These pages have been republished:

- http://dev-www.chapman.edu/a-z/index.aspx
- http://dev-www.chapman.edu/admission/undergraduate/contact-us/index.aspx#shannon-crogan
- http://dev-www.chapman.edu/campus-services/marketing-communication/guidelines-and-resources/writing/index.aspx
- http://dev-www.chapman.edu/students/policies-forms/student-conduct/conduct-code.aspx#Identification

**Comment by tatwell** [comment]
In address the root problem, anchors and a fixed navbar, this is the proper solution:

http://stackoverflow.com/questions/10732690/offsetting-an-html-anchor-to-adjust-for-fixed-header

The catch? It means adding an `anchor` class to markup throughout the site, including user-added WYSIWYG content.

**Comment by tatwell** [comment]
Release complete. Release plan here:

https://trello.com/c/92Fvbl9H/195-defect-omninav-bar-still-overlays-anchor-points-on-some-pages#comment-589e5710a10223debd0b9eb4
