### ISSUE TITLE
Logo not showing on Off-Canvas-Nav state where no college is selected.

### ISSUE THREAD

**Issue by waidelacruz** [chapmanu/cascade-assets#152]
Trello card detailing issue -
https://trello.com/c/NgUYJcdr/

**Comment by tatwell** [comment]
@waidelacruz Are you planning to handle this? If so, I'll assign you to this issue.

**Comment by waidelacruz** [comment]
@tatwell This was completed. Should I have closed this issue?

**Comment by tatwell** [comment]
@waidelacruz Yes, please close. If possible, link to related PR or commit. Also include any notes you think may be helpful to developers in future working on this or related issues. Thanks!

**Comment by waidelacruz** [comment]
Pull Request - https://github.com/chapmanu/cascade-assets/pull/154
