### ISSUE TITLE
Local dev server won't reload assets.

### ISSUE THREAD

**Issue by tatwell** [chapmanu/cascade-assets#222]
I made a change to a js file ('news-events.js`) and it took. But after a second change it won't reload the file.

I've tried the following without success:

- Restarted local server: CTRL-C > `rake serve`
- Stopped sprint and restarted server:

        spring stop
        rake serve
- Made another change to js file.

So far nothing has worked.

I vaguely recall encountering this issue before. But I can't find any record of how I fixed it. So I figured this time I'd record it here.

**Comment by tatwell** [comment]
Clobbering the assets seems to have solved the problem:

    rake assets:clobber

It deleted the directory `public/_assets`:

    Running via Spring preloader in process 91880
    I, [2017-07-21T15:16:25.894813 #91880]  INFO -- : Removed /Users/atwell/projects/cascade-assets/public/_assets

Not sure how that got there in the first place.

Fix seems to have stuck, too. I made a second change and it immediately took.

Found this solution here:

- https://stackoverflow.com/a/31517453/6763239

**Comment by tatwell** [comment]
Encountered a situation where `rake assets:clobber` didn't seem to work. Did the following:

- In console, killed server (if running): CTRL-C
- Ran following commands:

      rake tmp:clean
      rake assets:clobber
      rake assets:precompile

- Then restarted server

      rake server

I was also confused because the Chrome console was filtering out my log messages. So make sure a filter is not filtering out messages if you're using those to verify changes are taking.

**Comment by cbryant24** [comment]
Devs have recently run into this issue and running `bundle exex rake assets:precompile` solves the issue
