### ISSUE TITLE
In OmniNav 2 on Firefox, issue with hover on search/user icons.

### ISSUE THREAD

**Issue by tatwell** [chapmanu/cascade-assets#235]
Trello Card: https://trello.com/c/jAvZR52D/527-defect-in-omninav-2-on-firefox-issue-with-hover-on-search-user-icons

Discovered as part of this story:

- https://trello.com/c/XCUF4SDu/495-implement-wais-branded-masthead-design-for-the-new-omni-nav

Only an issue in Firefox. I looked up and down the stylesheet for a margin or padding setting that would explain it, but could not find one. Screenshot:

![firefox-icon-issue.png](https://trello-attachments.s3.amazonaws.com/57acf5c2d6c82399b130cbc5/598a124bc8c7b9b6d2e7df0c/e96ebc81b08df5bd9ac56418cb6d74fd/Screen_Shot_2017-08-24_at_9.00.41_AM.png) 

You should also be able to reproduce it locally on the demo page in the dev server.

I wouldn't consider it a showstopper, but it is unsightly.

**Comment by kaylaziegler** [comment]
Used a simplified JSFiddle to help figure out this issue: https://jsfiddle.net/2z85o02h/2/

**Comment by kaylaziegler** [comment]
I didn't really determine the exact line or lines that caused this issue, but I suspect it had to do with the relative and absolute positioning of the icons and text. I was the one who implemented this to start with, and there were some conflicting CSS rules. In PR #304 I stripped it down to the necessary rules and cleaned up that section in general so it's much more readable and I now know what every rule does.
