### ISSUE TITLE
As a Cascade User, I would like to see faster internal page load times.

### ISSUE THREAD

**Issue by kaylaziegler** [chapmanu/cascade-assets#239]
https://trello.com/c/1Hytt7sS/496-as-a-cascade-user-i-would-like-to-see-faster-internal-page-load-times

**Comment by kaylaziegler** [comment]
Helpful Velocity Programming Docs: http://velocity.apache.org/engine/1.7/user-guide.html

Location of test blocks and formats in Dev-Cascade: `_components/system_index_test`. It contains one test block for each option that Cascade provides. The current Omni-Nav format in use right now has been copied there. There are also 2 very simple new formats I wrote that are tailored to certain blocks. They do essentially the same thing but the parsing of the blocks is a little different. These formats are in use on the following pages:

- [Test Brute-Force](https://dev-cascade.chapman.edu/entity/open.act?id=3eec04d4c0a814531b32a4ac2e76ff75&type=page)
- [Test Siblings & Render Forward](https://dev-cascade.chapman.edu/entity/open.act?id=3e4d83edc0a814531b32a4aca832439e&type=page)

Test page rendering metrics:

- Block with everything: approx. 9917 ms
- Block with only siblings and rendering forward: approx. 129 ms

**Comment by kaylaziegler** [comment]
Trello stories have been spun off to rewrite formats in Cascade to work with different block:

- [In Dev Cascade, rewrite OmniNav Off-Canvas Nav using faster index block.](https://trello.com/c/v5qK35x8/542-in-cascade-rewrite-omninav-off-canvas-nav-using-faster-index-block)
- [In Dev Cascade, rewrite Global Nav using faster index block.](https://trello.com/c/J0OCb50y/545-in-dev-cascade-rewrite-left-column-menu-using-faster-index-block)
- [In Dev Cascade, rewrite Left Column Menu Block using faster index block.](https://trello.com/c/CbcLWyvb/546-in-dev-cascade-rewrite-global-nav-using-faster-index-block)

**Comment by kaylaziegler** [comment]
Trying to make sense of the left nav. Thoughts:

Question: What is considered a "sibling" in relation to the page you are currently on? We've got conflicting answers to this.

My answer: If you're on the index page (index.aspx) within a folder, I basically consider it the same thing as the folder even though it's on the same level hierarchically as other pages and folders. Those other pages and folders that are next to the index are considered children of the index.

Example:
- `copa/music/index.aspx` is the parent of `copa/music/admission/` folder and `copa/music/facilities.aspx`

If you're not on an index page, all the other pages and folders next to the index in the same parent folder are considered siblings to each other.

Example:

- `research/policies.aspx` page is a sibling of `research/integrity/` folder

We have 2 velocity formats currently in use for the left nav: `LeftNav_Velocity` and `LeftNavNoSiblings`. The name for `LeftNavNoSiblings` is misleading; it really means that the format does not _show_ any siblings, and is not an indication of whether or not the page _has_ siblings. It's more of a styling chose decided upon by the content team and theoretically any page could use either format.

**Comment by kaylaziegler** [comment]
If you look at the left nav on the following two pages (that are in the same folder), they are different despite using the same velocity format. Maybe there's some logic in the format that makes it behave differently if it is a certain index page?

- https://www.chapman.edu/copa/music/index.aspx
- https://www.chapman.edu/copa/music/facilities.aspx

**Comment by tatwell** [comment]
@mandythomas shared this document describing page and folder relationships:

- https://docs.google.com/document/d/1bvbpc28tVSSIIGFHhb3qLcv-TQeDRN39m_dzIXUN2r4/edit?usp=sharing

It confirms your conclusion above, @kaylaziegler:

> If you're on the index page (index.aspx) within a folder, I basically consider it the same thing as the folder even though it's on the same level hierarchically as other pages and folders.

From Mandy's document:

> The most important concept to keep in mind is that the index page is equivalent, or representative, of the folder itself.

**Comment by kaylaziegler** [comment]
Definition of Left Nav

`LeftNavNoSiblings` Velocity Format:

- Primarily used by index pages, confirm by looking at relationships for `_cascade/formats/level/LeftNavNoSiblings`
- The Left Nav shows all the children of the index page but no siblings of the index page (AKA folder)
- If the index page has children that are folders, it shows the children of those folders in dropdowns
- Basically only shows what is inside the folder you are currently in
- **Example**: https://www.chapman.edu/academics/index.aspx (The siblings of Academics include About, Arts, etc. and they are not shown)

`LeftNav_Velocity` Velocity Format:

- If on an index page:
  - Left Nav shows children of current page (no grandchildren)
  - Left Nav shows siblings of current page (folders and pages)
    - If a sibling has children, shows as a dropdown
  - **Example**: https://www.chapman.edu/copa/music/academic-programs/index.aspx
- If not on an index page:
  - Left Nav shows siblings of current page
    - If a sibling has children, shows as a dropdown
  - By definition, pages that aren't index can't have children, so no children shown
  - **Example**: https://www.chapman.edu/academics/general-education/global-citizen.aspx

**Comment by kaylaziegler** [comment]
Amazing docs with everything about Blocks in Cascade 8: https://www.hannonhill.com/cascadecms/8/kb/content-authoring/blocks/index-blocks.html

Where was this page like a week ago??

**Comment by tatwell** [comment]
I see page marked `Last Modified: 9/4/2017`. Did it literally appear within the last week? Lol.

**Comment by tatwell** [comment]
@kaylaziegler For `LeftNav_Velocity`, do you if the home page represents its own case or does it follow the index page rules?

**Comment by kaylaziegler** [comment]
@tatwell Do you mean the website home page, like www.chapman.edu? It doesn't have a left nav region so there's no format or block

**Comment by mandythomas** [comment]
@tatwell  and @kaylaziegler Even though the home page doesn't have a left nav region, the solutions to speeding up the the omni-nav off-canvas menu and the left-nav will likely have similiar/shared solutions, so keep in mind homepage does have the off-canvas menu, and uses the same LeftNav index "block" currently

**Comment by tatwell** [comment]
@kaylaziegler Sorry, I made a mistake. I was thinking about off-canvas-nav. But thanks for answering. Now it makes sense why it's not addressed.

Also, you're off today so you don't need to pay attention to this until you return to office.

**Comment by kaylaziegler** [comment]
This is how I'm thinking we should go about the left nav (exact names aren't final).

**Blocks:**
- `left_nav_siblings_render_fwd`
- `left_nav_all`

**Formats:**
- `left_nav_no_siblings`- meant to be used for index pages
- `left_nav_index`
- `left_nav`- for all pages that aren't an index page

The faster `left_nav_siblings_render_fwd` block will be used by `left_nav_no_siblings` and `left_nav` formats. The `left_nav_index` format needs to use the `left_nav_all` block, which is the brute-force slow block that's being used now. It needs info that's not in the smaller block and it's the only block that can be used without changing the functionality of those pages.

Thoughts?

**Comment by tatwell** [comment]
Looks good to me. Only problem is that `left_nav_all`. Are there other ways around it? Could we substitute some hardcoded params in the script like we do in the current OmniNav format to avoid it?

If there's not an obvious fix, I'm ok proceeding with this plan as an incremental improvement and then refocusing on eliminating `left_nav_all` as next step.

**Comment by kaylaziegler** [comment]
Well this is the problem I was expecting you to encounter as well, where you'll find that no other block than the one being used now will give you the data you need.

Example: https://dev-www.chapman.edu/copa/dance/index.aspx
Contents of the left nav on this page are the same as the off canvas nav. These index pages show siblings of the parent folder, technically, and you can only get that from the brute-force block. The new, faster block only gets siblings of the page and works downward from there.

My understanding of it is that the way we use/describe index pages hierarchically is something unique to us; even though it's in the same folder as other pages and folders, we treat them differently. But Cascade doesn't see it that way. The block given by "Start at the current page with folder hierarchy, siblings, and also render forward" just doesn't contain the information we currently use for index pages.

**Comment by tatwell** [comment]
That's a good example, @kaylaziegler . I see what you mean. Here are some screenshots to help clarify how things are structured:

#### User/WWW View of Left Nav

For user view of off-canvas-nav, [click here](https://user-images.githubusercontent.com/12798918/30339558-49519b2c-97a4-11e7-9236-9ef4a5423f62.png). Looks basically the same to my eye.

![screen shot 2017-09-12 at 10 19 17 am](https://user-images.githubusercontent.com/12798918/30339560-4b368ab0-97a4-11e7-8d00-3bd0c6e48bd3.png)

#### Admin/Cascade View of `copa` Directory

![screen shot 2017-09-12 at 10 21 35 am](https://user-images.githubusercontent.com/12798918/30339751-e18dfeee-97a4-11e7-987f-99863263714b.png)

#### Admin/Cascade View of `copa/dance` Directory

![screen shot 2017-09-12 at 10 19 46 am](https://user-images.githubusercontent.com/12798918/30339574-4cd9d318-97a4-11e7-985a-9a47fbc4e3df.png)

And so the problem is: to construct the view the user sees above, the index block would need to provide the VTL script with parent-sibling objects (e.g. `Chapman/edu/copa/message` file). But the only way to get it from that page context is using the brute force block.

What we need is an index block that goes one level up and one level down to deliver parent + parent-siblings + siblings + children items. As far as we know, Cascade doesn't do that.

**Comment by tatwell** [comment]
### Order Attribute of Block Index Objects

I also noticed from screenshot above that Cascade does provide an `order` attribute that our menus are using to order menu items. That explains why **Message from the Dean** is the first menu item listed.

**Comment by tatwell** [comment]
One idea: several index-blocks. If I'm not mistaken, the number is bound by this list from the OmniNav format:

```
#set ( $directories = ["/business", "/education", "/dodge", "/crean", "/wilkinson", "/copa", "/pharmacy", "/law", "/scst", "/about", "/academics", "/admission", "/alumni", "/campus-services", "/faculty-staff", "/families", "/research", "/students", "/support-chapman", "/communication"] )
```

So 20 index blocks. Ugh. And I suppose there would be other complications. Can a format be dynamically associated with a block?

**Comment by tatwell** [comment]
I thought Mandy said there might be another mechanism by which to query the file tree in Cascade. Maybe it's time to start looking into that if we haven't already.

**Comment by kaylaziegler** [comment]
She did give us this in an email: 

> The only other idea I’d had was using the LocatorTool to traverse the pages, instead of an index block at all. I think for big sections, it might actually be slower than it is now, but for little ones it might be faster. Maybe some Cascade user’s would get a benefit and the live site would remain as is. A thought.

If she's correct about it being bad for large sections, it wouldn't be the best option for the issue at hand

**Comment by kaylaziegler** [comment]
Note- the left nav block currently gets the system metadata in addition to some other data, but I removed that content from the new blocks. [This section](https://www.hannonhill.com/cascadecms/8/kb/content-authoring/blocks/index-blocks.html#IndexedAssetContent) of the Cascade docs shows what kind of info the system metadata contains and we do not use any of it in the formats, at least not for the left nav.

**Comment by kaylaziegler** [comment]
I think my 3 rewritten formats, located in `_components/left_nav`, are ready to be reviewed by the team. I guess we can just make comments here?

**Comment by tatwell** [comment]
As discussed, commit them in a new branch under .new cascade-code directory.

**Comment by mandythomas** [comment]
@kaylaziegler  I'm probably commenting really late in this development, and out of order from the various emails I've seen, but to one of your questions above, yes LeftNavNoSiblings is only a styling choice and not intended to be used automatically (or by election by client) just because a page is index or has no siblings or anything. It has nothing to do with any of those, it was simply an option the Web Coordinators could use to override what shows on some top pages. We probably shouldn't have brought it into the mix of the work you're doing here because I think it's confusing things.

**Comment by mandythomas** [comment]
@kaylaziegler  are you sure we don't need the Meta fields in the block? For the nav menus, we need the Display Name and the "Hide from navigation" checkbox field value. Those are housed in the Metadata Set callled "Page" which is one of the 3 parts of the Config Set.

**Comment by kaylaziegler** [comment]
@mandythomas Just in regards to your question: No we don't need the system metadata fields. If you read the docs that I linked to in that comment, you'll see we don't use those fields. The dynamic-metadata houses the "Hide from navigation" value, and that is under User Metadata. I have also tested that the block does work without the system metadata content, and I'm still able to filter out the hidden folders and pages.

**Comment by tatwell** [comment]
Yes, I checked the meta fields and, IIRC, they were all either unused IDs or timestamps. If there is a specific field that's used, let's note it.

I saw the fields somewhere recently and was going to paste them here but can't locate it at moment.

**Comment by tatwell** [comment]
Another useful debug tool:

- https://www.hannonhill.com/cascadecms/8/kb/developing-in-cascade/script-formats/velocity-tools.html#PropertyTool

We should add a Velocity page to Wiki with tips and code examples.

**Comment by tatwell** [comment]
We believe we have a solution in the works for this. It is based on this spike:

- TBA

It will require the format for both the OmniNav off-campus and LeftNav page menu be updated to use the Cascade Adapter API with the format `$currentPage` object. This will be implemented in these two stories:

- OmniNav: TBA
- LeftNav: TBA

**Comment by tatwell** [comment]
To close the issue, the new OmniNav and LeftNav formats will need to be released. Trello stories have been created:

- LeftNav Release: https://trello.com/c/4ekeO2Ms
- OmniNav Release: https://trello.com/c/jQdhBj4O

**Comment by kaylaziegler** [comment]
Production release for refactored left nav that doesn't use an index block is complete. Story: https://trello.com/c/4ekeO2Ms

I was able to remove the block from all pages that have a LeftNav region. See card comments for details.

Left nav region now loads in 0.5 seconds or less, on average. Page still renders slowly in Cascade CMS because the slow Left Nav index block is still in use by the OmniNav region.

**Comment by kaylaziegler** [comment]
Production release for new omninav is complete: https://trello.com/c/jQdhBj4O

Across the board, page load times within Cascade are around ~2 seconds (in Dev and production). None of the regions use the super-slow Left Nav index block that was causing the delays in loading. YAY!
